CC=gcc
SOURCES=../lib-spolks/tcp_wrap.c ../lib-spolks/utils.c
EXECUTABLE_CLIENT=client
EXECUTABLE_SERVER=server

all:

	$(CC) client.c $(SOURCES) -o $(EXECUTABLE_CLIENT)
	$(CC) server.c $(SOURCES) -o $(EXECUTABLE_SERVER)
