CC=gcc
SOURCES=../lib-spolks/utils.c ../lib-spolks/sockets_wrap.c
EXECUTABLE_CLIENT=client
EXECUTABLE_SERVER=server

all:

	$(CC) client.c $(SOURCES) -o $(EXECUTABLE_CLIENT)
	$(CC) server.c $(SOURCES) -o $(EXECUTABLE_SERVER)
