CC=gcc
SOURCES=main.c ../lib-spolks/tcp_wrap.c ../lib-spolks/utils.c
SOURCES_TEST=test.c ../lib-spolks/utils.c
EXECUTABLE=main
EXECUTABLE_TEST=test

all:

	$(CC) $(SOURCES) -o $(EXECUTABLE)
	$(CC) $(SOURCES_TEST) -o $(EXECUTABLE_TEST)
